---
format: 
  html:
    toc: false
    self-contained: true
    grid: 
      body-width: 1300px
server: shiny
---

```{r}
#| label: data and libraries
#| context: setup
#| echo: false
#| message: false
#| warning: false

# Libraries ----
library(here)
library(tidyverse)
library(gmRi)
library(matrixStats)
library(shiny)
library(rnaturalearthhires)
library(rnaturalearth)
library(rsconnect)

# Read in cleaned survey data ----
annual_centers <- read.csv(here("data", "annual_centers.csv"))
seasonal_centers <- read.csv(here("data", "seasonal_centers.csv"))
annual_percentiles <- read.csv(here("data", "annual_percentiles.csv"))

# Species input ----
species <- annual_centers |>
  select(comname) |> 
  distinct()
species <- species$comname

# Basemaps ---- 
usa <- ne_states(country = "united states of america", returnclass = "sf")
can <- ne_states(country = "canada", returnclass = "sf") 

# Means ----
annual_means <- annual_centers |>
  filter(year %in% c(1991:2022)) |> # 30 years with 2017,2020 removed
  pivot_longer(cols = "avg_lat":"avg_depth", names_to = "variable", values_to = "measurement") |>
  group_by(comname, variable) |>
  summarise(mean = mean(measurement)) |>
  pivot_wider(names_from = variable, values_from = "mean") |> 
  rename_with(~ str_remove(., "avg_"), everything()) 

```

```{r}
#| panel: fill

# Define UI
fluidPage(
  titlePanel("NMFS Species Distributions"),
  sidebarLayout(
    sidebarPanel(
      width = 2,
      selectInput("comname", "Select species:", 
                  choices = species,
                  selected = species[1]),
      hr()
    ),
    mainPanel(
      width = 10,
      tabsetPanel(
        tabPanel("Distributions", 
                 fluidRow(
                   column(5, plotOutput("latPlot", height = "300px")),
                   column(7, plotOutput("latPercentile", height = "300px")),
                   column(5, plotOutput("lonPlot", height = "300px")),
                   column(7, plotOutput("lonPercentile", height = "300px"))
                 )
        ),
        tabPanel("Environmental", 
                 fluidRow(
                   column(6, plotOutput("sstPlot", height = "250px")),
                   column(6, plotOutput("btPlot", height = "250px"))
                 ),
                 fluidRow(
                   column(12, plotOutput("depthPlot", height = "250px"))
                 )
        ),
        tabPanel("Maps", 
                 fluidRow(
                   column(12, plotOutput("seasonMap", height = "400px"))
                 )
        )
      )
    )
  )
)

```

```{r}
#| context: server
#| warning: false
#| message: false

# Filter data based on species selection ----

## seasonal data
filtered_season <- reactive({
  seasonal_centers |>
    filter(comname == input$comname)
})

## annual data
filtered_annual <- reactive({
  annual_centers |>
    left_join(annual_means) |>
    filter(comname == input$comname)
})

## percentiles
filtered_percentiles <- reactive({
  annual_percentiles|>
    filter(comname == input$comname)
})

# Map
output$seasonMap <- renderPlot({
  ggplot() +
    geom_sf(data = usa) + geom_sf(data = can) +
    coord_sf(xlim = c(-66, -78), ylim = c(35,45)) +
    geom_point(data = filtered_season(), aes(x = avg_lon, y = avg_lat, color = season)) + 
    guides(color = guide_legend(title = "Season")) + 
    scale_x_continuous(breaks = c(-66, -72, -78)) +
    scale_y_continuous(breaks = c(35, 40, 45)) +
    facet_wrap(~decade, nrow = 2) +
    scale_color_gmri() +
    theme_gmri(
      axis.title = element_blank(),
      legend.position = "bottom", 
      strip.background = element_rect(fill = "transparent"),
      strip.text = element_text(color = "#000000"), 
      panel.border = element_rect(color = "#6a6a6a", linetype = 1, fill = "transparent"),
      plot.margin = ( plot.margin = margin(0,0,0,0)))
})

# Lat plot
output$latPlot <- renderPlot({
  ggplot(filtered_annual()) +
      # geom_line(aes(x=year, y=(zoo::rollapplyr(avg_lat, width = 5, FUN = mean, align = "center", partial = T))), 
      #           linetype = 2, color = "#b94a40", linewidth = 1) + 
      geom_line(aes(x=year, y=avg_lat), linewidth = 0.8, alpha = 0.5)+
      geom_line(aes(x=year, y=lat), linetype = 2, linewidth = 1, color = "#07a3b7") + 
      ggtitle("Center of latitude", subtitle = "Average latitude weighted by biomass") +
      ylab("Latitude") +
      theme_gmri(
        axis.title.x  = element_blank(), 
        plot.subtitle = element_text(size = 11))
})

# Lon plot
output$lonPlot <- renderPlot({
  ggplot(filtered_annual()) +
      geom_line(aes(x=year, y=avg_lon), linewidth = 0.8, alpha = 0.5)+
      geom_line(aes(x=year, y=lon), linetype = 2, linewidth = 1, color = "#ebcb27") +
      ggtitle("Center of longitude", subtitle = "Average longitude weighted by biomass") +
      ylab("Longitude") +
      theme_gmri(
        axis.title.x  = element_blank(),
        plot.subtitle = element_text(size = 11))
})


# SST plot
output$sstPlot <- renderPlot({
  ggplot(filtered_annual()) +
      geom_line(aes(x=year, y=avg_sst), linewidth = 0.8, alpha = 0.5)+
      geom_line(aes(x = year, y=sst), color = "#b94a40", linetype = 2, linewidth = 1) +
      ggtitle("Average Sea Surface Temperature", subtitle = "Weighted by biomass") +
      ylab("Temperature") +
      theme_gmri(
        axis.title.x  = element_blank(),
        plot.subtitle = element_text(size = 11))
})

# BT plot
output$btPlot <- renderPlot({
  ggplot(filtered_annual()) +
      geom_line(aes(x=year, y=avg_bot), linewidth = 0.8)+
      geom_line(aes(x = year, y = bot), color = "#004966", linetype = 2, linewidth = 1) +
      ggtitle("Average Bottom Temperature", subtitle = "Weighted by biomass") +
      ylab("Temperature") +
      theme_gmri(
        axis.title.x  = element_blank(),
        plot.subtitle = element_text(size = 11))
})

# Depth plot
output$depthPlot <- renderPlot({
  ggplot(filtered_annual()) +
      geom_line(aes(x=year, y=avg_depth), linewidth = 0.8)+
      geom_line(aes(x = year, y = depth), color = "#773891", linetype = 2, linewidth = 1) +
      scale_y_reverse() +
      ggtitle("Average Depth", subtitle = "Weighted by biomass") +
      ylab("Depth") +
      theme_gmri(
        axis.title.x  = element_blank(),
        plot.subtitle = element_text(size = 11))
})

# Percentiles 
## Lat
output$latPercentile <- renderPlot({
  ggplot(reactive({
  annual_percentiles|>
      mutate(factor = factor(percentiles, levels = c("5%","25%","50%","75%","95%"))) |>
      filter(variable == "lat" & comname == input$comname)
})()) +
      geom_line(aes(x = year, y = roll_mean, color = factor), linetype = 2, linewidth = 1) +
      geom_line(aes(x = year, y = measurement, color = factor), alpha = 0.25, linewidth = 1) +
      ggtitle("Biomass-weighted latitude percentiles", subtitle = "5-year rolling mean represented by dashed line") +
      ylab("Latitude") +
      scale_color_gmri() +
    theme_gmri(
      axis.title.x = element_blank(),
      plot.subtitle = element_text(size = 11),
      legend.position = "right"
    )
})

## Lon
output$lonPercentile <- renderPlot({
  ggplot(reactive({
  annual_percentiles|>
       mutate(factor = factor(percentiles, levels = c("5%","25%","50%","75%","95%"))) |>
       filter(variable == "lon" & comname == input$comname)
})()) +
      geom_line(aes(x = year, y = roll_mean,   color = factor), linetype = 2, linewidth = 1) +
      geom_line(aes(x = year, y = measurement, color = factor), alpha = 0.25, linewidth = 1) +
      ggtitle("Biomass-weighted longitude percentiles", subtitle = "5-year rolling mean represented by dashed line") +
      ylab("Longitude") +
      scale_color_gmri() +
    theme_gmri(
      axis.title.x = element_blank(),
      plot.subtitle = element_text(size = 11),
      legend.position = "right"
    )
})
```